<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxpxkj8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxpxkj8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUxpxkj8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUxpxkj8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUxpxkj8\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uxpxkj8',
    'container.build_id' => '43474796',
    'container.build_time' => 1532787815,
));
